// ARQUIVO DE DADOS DO DESENVOLVEDOR: Adicione novos elementos, altere raridades ou alterne estados de não lançado aqui.
const baseSprites = [
    { id: "water_basic", name: "Água", theme: "Basic", rarity: "Rare", unreleased: false },
    { id: "water_gold", name: "Água Dourada", theme: "Gold", rarity: "Special", unreleased: false },
    { id: "water_candy", name: "Água de Gelatina", theme: "Candy", rarity: "Special", unreleased: false },
    { id: "water_galaxy", name: "Água Galáxia", theme: "Galaxy", rarity: "Special", unreleased: false },
    { id: "water_gem", name: "Água Gema", theme: "Gem", rarity: "Special", unreleased: true },
    { id: "water_holofoil", name: "Água Holofoil", theme: "Holofoil", rarity: "Special", unreleased: true },
    
    { id: "earth_basic", name: "Terra", theme: "Basic", rarity: "Rare", unreleased: false },
    { id: "earth_gold", name: "Terra Dourada", theme: "Gold", rarity: "Special", unreleased: false },
    { id: "earth_candy", name: "Terra de Gelatina", theme: "Candy", rarity: "Special", unreleased: false },
    { id: "earth_galaxy", name: "Terra Galáxia", theme: "Galaxy", rarity: "Special", unreleased: false },
    { id: "earth_gem", name: "Terra Gema", theme: "Gem", rarity: "Special", unreleased: true },
    
    { id: "fire_basic", name: "Fogo", theme: "Basic", rarity: "Rare", unreleased: false },
    { id: "fire_gold", name: "Fogo Dourado", theme: "Gold", rarity: "Special", unreleased: false },
    { id: "fire_candy", name: "Fogo de Gelatina", theme: "Candy", rarity: "Special", unreleased: false },
    { id: "fire_galaxy", name: "Fogo Galáxia", theme: "Galaxy", rarity: "Special", unreleased: false },
    { id: "fire_holofoil", name: "Fogo Holofoil", theme: "Holofoil", rarity: "Special", unreleased: true },

    { id: "duck_basic", name: "Pato", theme: "Basic", rarity: "Epic", unreleased: false },
    { id: "duck_gold", name: "Pato Dourado", theme: "Gold", rarity: "Special", unreleased: false },
    { id: "duck_candy", name: "Pato de Gelatina", theme: "Candy", rarity: "Special", unreleased: false },
    { id: "duck_galaxy", name: "Pato Galáxia", theme: "Galaxy", rarity: "Special", unreleased: false },
    { id: "duck_gem", name: "Pato Gema", theme: "Gem", rarity: "Special", unreleased: true },
	
    { id: "ghost_basic", name: "Fantasma", theme: "Basic", rarity: "Epic", unreleased: false },
    { id: "ghost_gold", name: "Fantasma Dourado", theme: "Gold", rarity: "Special", unreleased: false },
    { id: "ghost_candy", name: "Fantasma de Gelatina", theme: "Candy", rarity: "Special", unreleased: false },
    { id: "ghost_galaxy", name: "Fantasma Galáxia", theme: "Galaxy", rarity: "Special", unreleased: false },
    { id: "ghost_holofoil", name: "Fantasma Holofoil", theme: "Holofoil", rarity: "Special", unreleased: true },
	
    { id: "dream_basic", name: "Sonho", theme: "Basic", rarity: "Legendary", unreleased: false },
    { id: "dream_gold", name: "Sonho Dourado", theme: "Gold", rarity: "Special", unreleased: false },
    { id: "dream_candy", name: "Sonho de Gelatina", theme: "Candy", rarity: "Special", unreleased: false },
    { id: "dream_galaxy", name: "Sonho Galáxia", theme: "Galaxy", rarity: "Special", unreleased: false },
    { id: "dream_rift", name: "Sonho Fenda", theme: "Rift", rarity: "Special", unreleased: true },
	
    { id: "demon_basic", name: "Demônio", theme: "Basic", rarity: "Epic", unreleased: false },
    { id: "demon_gold", name: "Demônio Dourado", theme: "Gold", rarity: "Special", unreleased: false },
    { id: "demon_candy", name: "Demônio de Gelatina", theme: "Candy", rarity: "Special", unreleased: false },
	{ id: "demon_galaxy", name: "Demônio Galáxia", theme: "Galaxy", rarity: "Special", unreleased: false },
    { id: "demon_gem", name: "Demônio Gema", theme: "Gem", rarity: "Special", unreleased: true },

	{ id: "punk_basic", name: "Punk", theme: "Basic", rarity: "Legendary", unreleased: false },
    { id: "punk_gold", name: "Punk Dourado", theme: "Gold", rarity: "Special", unreleased: false },
    { id: "punk_candy", name: "Punk de Gelatina", theme: "Candy", rarity: "Special", unreleased: false },
    { id: "punk_galaxy", name: "Punk Galáxia", theme: "Galaxy", rarity: "Special", unreleased: false },
    { id: "punk_gem", name: "Punk Gema", theme: "Gem", rarity: "Special", unreleased: true },
    { id: "punk_rift", name: "Punk Fenda", theme: "Rift", rarity: "Special", unreleased: true },

	{ id: "king_basic", name: "Rei", theme: "Basic", rarity: "Epic", unreleased: false },
    { id: "king_gold", name: "Rei Dourado", theme: "Gold", rarity: "Special", unreleased: false },
    { id: "king_candy", name: "Rei de Gelatina", theme: "Candy", rarity: "Special", unreleased: false },
    { id: "king_galaxy", name: "Rei Galáxia", theme: "Galaxy", rarity: "Special", unreleased: false },
    { id: "king_holofoil", name: "Rei Holofoil", theme: "Holofoil", rarity: "Special", unreleased: true },

    { id: "zeropoint_basic", name: "Ponto Zero", theme: "Basic", rarity: "Mythic", unreleased: false },
    { id: "zeropoint_gold", name: "Ponto Zero Dourado", theme: "Gold", rarity: "Special", unreleased: false },
    { id: "zeropoint_candy", name: "Ponto Zero de Gelatina", theme: "Candy", rarity: "Special", unreleased: false },
    { id: "zeropoint_galaxy", name: "Ponto Zero Galáxia", theme: "Galaxy", rarity: "Special", unreleased: false },
    { id: "zeropoint_gem", name: "Ponto Zero Gema", theme: "Gem", rarity: "Special", unreleased: true },
    { id: "zeropoint_holofoil", name: "Ponto Zero Quack", theme: "Holofoil", rarity: "Special", unreleased: true },
	
    { id: "theburntpeanut_basic", name: "Amendoim Queimado", theme: "Basic", rarity: "Mythic", unreleased: false },
	
    { id: "fishy_basic", name: "Peixoto", theme: "Basic", rarity: "Rare", unreleased: false },
    { id: "fishy_gold", name: "Peixoto Dourado", theme: "Gold", rarity: "Special", unreleased: false },
    { id: "fishy_candy", name: "Peixoto de Gelatina", theme: "Candy", rarity: "Special", unreleased: false },
    { id: "fishy_galaxy", name: "Peixoto Galáxia", theme: "Galaxy", rarity: "Special", unreleased: false },
	//	{ id: "fishy_gem", name: "Gem Fishy", theme: "Gem", rarity: "Special", unreleased: true },
	//	{ id: "fishy_holofoil", name: "Holofoil Fishy", theme: "Holofoil", rarity: "Special", unreleased: true },

    { id: "striker_basic", name: "Atacante", theme: "Basic", rarity: "Epic", unreleased: false },
    { id: "striker_gold", name: "Atacante Dourado", theme: "Gold", rarity: "Special", unreleased: false },
    { id: "striker_candy", name: "Atacante de Gelatina", theme: "Candy", rarity: "Special", unreleased: false },
    { id: "striker_galaxy", name: "Atacante Galáxia", theme: "Galaxy", rarity: "Special", unreleased: false },
    //	{ id: "striker_gem", name: "Gem Striker", theme: "Gem", rarity: "Special", unreleased: true },
    { id: "striker_holofoil", name: "Atacante Holofoil", theme: "Holofoil", rarity: "Special", unreleased: true },

    { id: "aura_basic", name: "Aura", theme: "Basic", rarity: "Epic", unreleased: false },
    { id: "aura_gold", name: "Aura Dourada", theme: "Gold", rarity: "Special", unreleased: false },
    { id: "aura_candy", name: "Aura de Gelatina", theme: "Candy", rarity: "Special", unreleased: false },
    { id: "aura_galaxy", name: "Aura Galáxia", theme: "Galaxy", rarity: "Special", unreleased: false },
    { id: "aura_gem", name: "Aura Gema", theme: "Gem", rarity: "Special", unreleased: true },
	//	{ id: "aura_holofoil", name: "Holofoil Aura", theme: "Holofoil", rarity: "Special", unreleased: true },

    { id: "boss_basic", name: "Chefe", theme: "Basic", rarity: "Legendary", unreleased: false },
    { id: "boss_gold", name: "Chefe Dourado", theme: "Gold", rarity: "Special", unreleased: false },
    { id: "boss_candy", name: "Chefe de Gelatina", theme: "Candy", rarity: "Special", unreleased: false },
    { id: "boss_galaxy", name: "Chefe Galáxia", theme: "Galaxy", rarity: "Special", unreleased: false },
	//	{ id: "boss_gem", name: "Gem Boss", theme: "Gem", rarity: "Special", unreleased: true },
	//	{ id: "boss_holofoil", name: "Holofoil Boss", theme: "Holofoil", rarity: "Special", unreleased: true },

    { id: "grim_basic", name: "Sinistro", theme: "Basic", rarity: "Mythic", unreleased: false },
    { id: "grim_gold", name: "Sinistro Dourado", theme: "Gold", rarity: "Special", unreleased: false },
    { id: "grim_candy", name: "Sinistro de Gelatina", theme: "Candy", rarity: "Special", unreleased: false },
    { id: "grim_galaxy", name: "Sinistro Galáxia", theme: "Galaxy", rarity: "Special", unreleased: false },
	//	{ id: "grim_gem", name: "Gem Grim", theme: "Gem", rarity: "Special", unreleased: true },
	//	{ id: "grim_holofoil", name: "Holofoil Grim", theme: "Holofoil", rarity: "Special", unreleased: true },

    { id: "air_basic", name: "Ar", theme: "Basic", rarity: "Rare", unreleased: true },
    { id: "air_gold", name: "Ar Dourado", theme: "Gold", rarity: "Special", unreleased: true },
    { id: "air_candy", name: "Ar de Gelatina", theme: "Candy", rarity: "Special", unreleased: true },
    { id: "air_galaxy", name: "Ar Galáxia", theme: "Galaxy", rarity: "Special", unreleased: true },
	//	{ id: "air_gem", name: "Gem Air", theme: "Gem", rarity: "Special", unreleased: true },
    { id: "air_holofoil", name: "Ar Holofoil", theme: "Holofoil", rarity: "Special", unreleased: true },
	
    { id: "seven_basic", name: "Sete", theme: "Basic", rarity: "Legendary", unreleased: true },
    { id: "seven_gold", name: "Sete Dourado", theme: "Gold", rarity: "Special", unreleased: true },
    { id: "seven_candy", name: "Sete de Gelatina", theme: "Candy", rarity: "Special", unreleased: true },
    { id: "seven_galaxy", name: "Sete Galáxia", theme: "Galaxy", rarity: "Special", unreleased: true },
	//	{ id: "seven_gem", name: "Gem Seven", theme: "Gem", rarity: "Special", unreleased: true },
    { id: "seven_holofoil", name: "Sete Holofoil", theme: "Holofoil", rarity: "Special", unreleased: true },

	{ id: "wick_basic", name: "John Wick", theme: "Basic", rarity: "Mythic", unreleased: true },
];