
const baseSprites = [
    { id: "water_basic", name: "Água", theme: "Básico", rarity: "Raro", unreleased: false },
    { id: "water_gold", name: "Água de Ouro", theme: "Ouro", rarity: "Especial", unreleased: false },
    { id: "water_candy", name: "Água Gelatinosa", theme: "Doce", rarity: "Especial", unreleased: false },
    { id: "water_galaxy", name: "Água Galáxia", theme: "Galáxia", rarity: "Especial", unreleased: false },
    { id: "water_gem", name: "Água de Joia", theme: "Joia", rarity: "Especial", unreleased: true },
    { id: "water_holofoil", name: "Água Metalizada", theme: "Metalizado", rarity: "Especial", unreleased: false },
    
    { id: "earth_basic", name: "Terra", theme: "Básico", rarity: "Raro", unreleased: false },
    { id: "earth_gold", name: "Terra de Ouro", theme: "Ouro", rarity: "Especial", unreleased: false },
    { id: "earth_candy", name: "Terra Gelatinosa", theme: "Doce", rarity: "Especial", unreleased: false },
    { id: "earth_galaxy", name: "Terra Galáxia", theme: "Galáxia", rarity: "Especial", unreleased: false },
    { id: "earth_gem", name: "Terra de Joia", theme: "Joia", rarity: "Especial", unreleased: true },
    { id: "earth_rift", name: "Terra da Fenda", theme: "Fenda", rarity: "Especial", unreleased: true },

    { id: "fire_basic", name: "Fogo", theme: "Básico", rarity: "Raro", unreleased: false },
    { id: "fire_gold", name: "Fogo de Ouro", theme: "Ouro", rarity: "Especial", unreleased: false },
    { id: "fire_candy", name: "Fogo Gelatinoso", theme: "Doce", rarity: "Especial", unreleased: false },
    { id: "fire_galaxy", name: "Fogo Galáxia", theme: "Galáxia", rarity: "Especial", unreleased: false },
    { id: "fire_holofoil", name: "Fogo Metalizado", theme: "Metalizado", rarity: "Especial", unreleased: false },
	{ id: "fire_rift", name: "Fogo da Fenda", theme: "Fenda", rarity: "Especial", unreleased: true },
	
    { id: "duck_basic", name: "Pato", theme: "Básico", rarity: "Épico", unreleased: false },
    { id: "duck_gold", name: "Pato de Ouro", theme: "Ouro", rarity: "Especial", unreleased: false },
    { id: "duck_candy", name: "Pato Gelatinoso", theme: "Doce", rarity: "Especial", unreleased: false },
    { id: "duck_galaxy", name: "Pato Galáxia", theme: "Galáxia", rarity: "Especial", unreleased: false },
    { id: "duck_gem", name: "Pato de Joia", theme: "Joia", rarity: "Especial", unreleased: true },
	
    { id: "ghost_basic", name: "Fantasma", theme: "Básico", rarity: "Épico", unreleased: false },
    { id: "ghost_gold", name: "Fantasma de Ouro", theme: "Ouro", rarity: "Especial", unreleased: false },
    { id: "ghost_candy", name: "Fantasma Gelatinoso", theme: "Doce", rarity: "Especial", unreleased: false },
    { id: "ghost_galaxy", name: "Fantasma Galáxia", theme: "Galáxia", rarity: "Especial", unreleased: false },
    { id: "ghost_holofoil", name: "Fantasma Metalizado", theme: "Metalizado", rarity: "Especial", unreleased: false },
	
    { id: "dream_basic", name: "Sonho", theme: "Básico", rarity: "Lendário", unreleased: false },
    { id: "dream_gold", name: "Sonho de Ouro", theme: "Ouro", rarity: "Especial", unreleased: false },
    { id: "dream_candy", name: "Sonho Gelatinoso", theme: "Doce", rarity: "Especial", unreleased: false },
    { id: "dream_galaxy", name: "Sonho Galáxia", theme: "Galáxia", rarity: "Especial", unreleased: false },
    { id: "dream_rift", name: "Sonho da Fenda", theme: "Fenda", rarity: "Especial", unreleased: true },
	
    { id: "demon_basic", name: "Demônio", theme: "Básico", rarity: "Épico", unreleased: false },
    { id: "demon_gold", name: "Demônio de Ouro", theme: "Ouro", rarity: "Especial", unreleased: false },
    { id: "demon_candy", name: "Demônio Gelatinoso", theme: "Doce", rarity: "Especial", unreleased: false },
	{ id: "demon_galaxy", name: "Demônio Galáxia", theme: "Galáxia", rarity: "Especial", unreleased: false },
    { id: "demon_gem", name: "Demônio de Joia", theme: "Joia", rarity: "Especial", unreleased: true },

	{ id: "punk_basic", name: "Punk", theme: "Básico", rarity: "Lendário", unreleased: false },
    { id: "punk_gold", name: "Punk de Ouro", theme: "Ouro", rarity: "Especial", unreleased: false },
    { id: "punk_candy", name: "Punk Gelatinoso", theme: "Doce", rarity: "Especial", unreleased: false },
    { id: "punk_galaxy", name: "Punk Galáxia", theme: "Galáxia", rarity: "Especial", unreleased: false },
    { id: "punk_gem", name: "Punk de Joia", theme: "Joia", rarity: "Especial", unreleased: true },
    { id: "punk_rift", name: "Punk da Fenda", theme: "Fenda", rarity: "Especial", unreleased: true },

	{ id: "king_basic", name: "Rei", theme: "Básico", rarity: "Épico", unreleased: false },
    { id: "king_gold", name: "Rei de Ouro", theme: "Ouro", rarity: "Especial", unreleased: false },
    { id: "king_candy", name: "Rei Gelatinoso", theme: "Doce", rarity: "Especial", unreleased: false },
    { id: "king_galaxy", name: "Rei Galáxia", theme: "Galáxia", rarity: "Especial", unreleased: false },
    { id: "king_holofoil", name: "Rei Metalizado", theme: "Metalizado", rarity: "Especial", unreleased: false },

    { id: "zeropoint_basic", name: "Ponto Zero", theme: "Básico", rarity: "Mítico", unreleased: false },
    { id: "zeropoint_gold", name: "Ponto Zero de Ouro", theme: "Ouro", rarity: "Especial", unreleased: false },
    { id: "zeropoint_candy", name: "Ponto Zero Gelatinoso", theme: "Doce", rarity: "Especial", unreleased: false },
    { id: "zeropoint_galaxy", name: "Ponto Zero Galáxia", theme: "Galáxia", rarity: "Especial", unreleased: false },
    { id: "zeropoint_gem", name: "Ponto Zero de Joia", theme: "Joia", rarity: "Especial", unreleased: true },
    { id: "zeropoint_holofoil", name: "Ponto Zero Quack", theme: "Metalizado", rarity: "Especial", unreleased: true },
	
    { id: "theburntpeanut_basic", name: "Amendoim Queimado", theme: "Básico", rarity: "Mítico", unreleased: false },
	
    { id: "fishy_basic", name: "Peixe", theme: "Básico", rarity: "Raro", unreleased: false },
    { id: "fishy_gold", name: "Peixe de Ouro", theme: "Ouro", rarity: "Especial", unreleased: false },
    { id: "fishy_candy", name: "Peixe Gelatinoso", theme: "Doce", rarity: "Especial", unreleased: false },
    { id: "fishy_galaxy", name: "Peixe Galáxia", theme: "Galáxia", rarity: "Especial", unreleased: false },
	//	{ id: "fishy_gem", name: "Peixe de Joia", theme: "Joia", rarity: "Especial", unreleased: true },
	//	{ id: "fishy_holofoil", name: "Peixe Metalizado", theme: "Metalizado", rarity: "Especial", unreleased: true },
	{ id: "fishy_rift", name: "Peixe da Fenda", theme: "Fenda", rarity: "Especial", unreleased: true },
	
    { id: "striker_basic", name: "Atacante", theme: "Básico", rarity: "Épico", unreleased: false },
    { id: "striker_gold", name: "Atacante de Ouro", theme: "Ouro", rarity: "Especial", unreleased: false },
    { id: "striker_candy", name: "Atacante Gelatinoso", theme: "Doce", rarity: "Especial", unreleased: false },
    { id: "striker_galaxy", name: "Atacante Galáxia", theme: "Galáxia", rarity: "Especial", unreleased: false },
    //	{ id: "striker_gem", name: "Atacante de Joia", theme: "Joia", rarity: "Especial", unreleased: true },
    { id: "striker_holofoil", name: "Atacante Metalizado", theme: "Metalizado", rarity: "Especial", unreleased: false },

    { id: "aura_basic", name: "Aura", theme: "Básico", rarity: "Épico", unreleased: false },
    { id: "aura_gold", name: "Aura de Ouro", theme: "Ouro", rarity: "Especial", unreleased: false },
    { id: "aura_candy", name: "Aura Gelatinosa", theme: "Doce", rarity: "Especial", unreleased: false },
    { id: "aura_galaxy", name: "Aura Galáxia", theme: "Galáxia", rarity: "Especial", unreleased: false },
    { id: "aura_gem", name: "Aura de Joia", theme: "Joia", rarity: "Especial", unreleased: true },
	//	{ id: "aura_holofoil", name: "Aura Metalizada", theme: "Metalizado", rarity: "Especial", unreleased: true },

    { id: "boss_basic", name: "Chefe", theme: "Básico", rarity: "Lendário", unreleased: false },
    { id: "boss_gold", name: "Chefe de Ouro", theme: "Ouro", rarity: "Especial", unreleased: false },
    { id: "boss_candy", name: "Chefe Gelatinoso", theme: "Doce", rarity: "Especial", unreleased: false },
    { id: "boss_galaxy", name: "Chefe Galáxia", theme: "Galáxia", rarity: "Especial", unreleased: false },
	//	{ id: "boss_gem", name: "Chefe de Joia", theme: "Joia", rarity: "Especial", unreleased: true },
	//	{ id: "boss_holofoil", name: "Chefe Metalizado", theme: "Metalizado", rarity: "Especial", unreleased: true },
	{ id: "boss_rift", name: "Chefe da Fenda", theme: "Fenda", rarity: "Especial", unreleased: true },


    { id: "grim_basic", name: "Ceifador", theme: "Básico", rarity: "Mítico", unreleased: false },
    { id: "grim_gold", name: "Ceifador de Ouro", theme: "Ouro", rarity: "Especial", unreleased: false },
    { id: "grim_candy", name: "Ceifador Gelatinoso", theme: "Doce", rarity: "Especial", unreleased: false },
    { id: "grim_galaxy", name: "Ceifador Galáxia", theme: "Galáxia", rarity: "Especial", unreleased: false },
	//	{ id: "grim_gem", name: "Ceifador de Joia", theme: "Joia", rarity: "Especial", unreleased: true },
	//	{ id: "grim_holofoil", name: "Ceifador Metalizado", theme: "Metalizado", rarity: "Especial", unreleased: true },
	{ id: "grim_rift", name: "Ceifador da Fenda", theme: "Fenda", rarity: "Especial", unreleased: true },

    { id: "air_basic", name: "Ar", theme: "Básico", rarity: "Raro", unreleased: false },
    { id: "air_gold", name: "Ar de Ouro", theme: "Ouro", rarity: "Especial", unreleased: false },
    { id: "air_candy", name: "Ar Gelatinoso", theme: "Doce", rarity: "Especial", unreleased: false },
    { id: "air_galaxy", name: "Ar Galáxia", theme: "Galáxia", rarity: "Especial", unreleased: false },
	//	{ id: "air_gem", name: "Ar de Joia", theme: "Joia", rarity: "Especial", unreleased: false },
    { id: "air_holofoil", name: "Ar Metalizado", theme: "Metalizado", rarity: "Especial", unreleased: false },
	
    { id: "seven_basic", name: "Sete", theme: "Básico", rarity: "Lendário", unreleased: false },
    { id: "seven_gold", name: "Sete de Ouro", theme: "Ouro", rarity: "Especial", unreleased: false },
    { id: "seven_candy", name: "Sete Gelatinoso", theme: "Doce", rarity: "Especial", unreleased: false },
    { id: "seven_galaxy", name: "Sete Galáxia", theme: "Galáxia", rarity: "Especial", unreleased: false },
	//	{ id: "seven_gem", name: "Sete de Joia", theme: "Joia", rarity: "Especial", unreleased: false },
    { id: "seven_holofoil", name: "Sete Metalizado", theme: "Metalizado", rarity: "Especial", unreleased: false },

	{ id: "batman_basic", name: "Batman", theme: "Básico", rarity: "Mítico", unreleased: false },
    { id: "batman_gold", name: "Batman de Ouro", theme: "Ouro", rarity: "Especial", unreleased: false },
    { id: "batman_candy", name: "Batman Gelatinoso", theme: "Doce", rarity: "Especial", unreleased: false },
    { id: "batman_galaxy", name: "Batman Galáxia", theme: "Galáxia", rarity: "Especial", unreleased: false },
    //	{ id: "batman_gem", name: "Batman de Joia", theme: "Joia", rarity: "Especial", unreleased: true },
    { id: "batman_holofoil", name: "Batman Metalizado", theme: "Metalizado", rarity: "Especial", unreleased: false },
	{ id: "batman_rift", name: "Batman da Fenda", theme: "Fenda", rarity: "Especial", unreleased: true },

	{ id: "pollo_basic", name: "Pollo", theme: "Básico", rarity: "Mítico", unreleased: true },

	{ id: "vini_basic", name: "Vini Jr.", theme: "Básico", rarity: "Mítico", unreleased: false },
	
	{ id: "wick_basic", name: "John Wick", theme: "Básico", rarity: "Mítico", unreleased: true },

];